# Generated by Django 5.2 on 2025-04-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="credential_id",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="credential_public_key",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sign_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(name="MagicLink",),
    ]
